{% set name = "votca" %}
{% set version = "2024.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/votca/votca/archive/v{{ version }}.tar.gz
  sha256: 704d50f64bbfa2e19d0aa4b5726ac35c20c3b9b45554be5f1e1417d430e31c24

build:
  number: 1
  skip: true  # [not linux]
  skip: true  # [py < 38]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - make
    - cmake
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
  host:
    - python
    - pytest
    - valgrind
    - expat
    - fftw
    - libboost-devel
    - libxc
    - hdf5
    - eigen
    - rdkit
    - libint
    - libecpint
    - lxml
    - h5py
    - gromacs
  run:
    - python
    - libint
    - lxml
    - gromacs

test:
  commands:
    - votca_property --help
    - csg_boltzmann --help
    - csg_gmxtopol --help
    - csg_map --help
    - csg_stat --help
    - csg_resample --help
    - csg_call --help
    - csg_boltzmann --help
    - csg_inverse --help
    - csg_density --help
    - csg_dlptopol --help
    - csg_dump --help
    - csg_fmatch --help
    - csg_imc_solve --help
    - csg_property --help
    - csg_reupdate --help
    - xtp_basisset --help  # [py > 39] 
    - xtp_update_mapfile --help  # [py > 39]
    - xtp_modify_jobfile --help  # [py > 39]

about:
  home: https://www.votca.org
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Versatile Object-oriented Toolkit for Coarse-graining Applications (VOTCA)'
  description: |
    VOTCA is a software package which focuses on the analysis of
    molecular dynamics data, the development of systematic coarse-graining
    techniques as well as methods used for simulating microscopic charge
    (and exciton) transport in disordered semiconductors. Its C++ core is
    interfaced to Bash and Perl flow-control scripts.
  doc_url: https://www.votca.org
  dev_url: https://github.com/votca/votca

extra:
  recipe-maintainers:
    - jan-janssen
